// Code generated by grom. DO NOT EDIT.
// Code generated by grom. DO NOT EDIT.
// Code generated by grom. DO NOT EDIT.

package {{.PackageName}}

{{ if .NeedImport }}
import (
	{{ if .EnableGureguNull }}
		"gopkg.in/guregu/null.v4"
	{{ else if .EnableSQLNull }}
		"database/sql"
	{{ else if .EnableGoTime }}
		"time"
	{{ end }}
	{{ if .EnableDataTypes }}"gorm.io/datatypes"{{ end }}
	{{ if .EnableGROM }}"gorm.io/gorm"{{ end }}
)
{{ end }}

// TableName{{ .StructName }} represents the table name of the {{ .StructName }} model
const TableName{{ .StructName }} = "{{ .Table }}"

// {{ .StructName }} {{ .TableComment }}
type {{ .StructName }} struct {
	{{ range .StructFields -}}
		{{ .Name }} {{ .Type }} {{ .Tag }}
		{{- if and $.EnableFieldComment .Comment }}// {{ .Comment }}{{ end }}
	{{ end -}}
}

{{ if .EnableTableName }}
// TableName returns the table name of the {{ .StructName }} model
func ({{ .ShortStructName }} *{{ .StructName }}) TableName() string {
	return TableName{{ .StructName }}
}
{{ end }}

{{ if .EnableTableIndex }}
// TableIndex returns the table indexes of the {{ .StructName }} model
func ({{ .ShortStructName }} *{{ .StructName }}) TableIndex() [][]string {
	return [][]string{
		{{ range .TableIndexes -}}
			{ {{ . }} },
		{{ end }}
	}
}
{{ end }}

{{ if .EnableTableUnique }}
// TableUnique returns the table unique indexes of the {{ .StructName }} model
func ({{ .ShortStructName }} *{{ .StructName }}) TableUnique() [][]string {
	return [][]string{
		{{ range .TableUniques -}}
			{ {{ . }} },
		{{ end }}
	}
}
{{ end }}